spring:
  datasource:
    username: kento
    password: password
    url: jdbc:mysql://localhost:3307/batch_db
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect

  batch:
    jdbc:
      initialize-schema: ALWAYS
    job:
      enabled: false

server:
  port: 8081